
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVuEANZ0eVetmOXdDBxqeFmIQ-W-SiwjY',
    authDomain: 'calendarapp-86d88.firebaseapp.com',
    databaseURL: 'https://calendarapp-86d88-default-rtdb.firebaseio.com',
    projectId: 'calendarapp-86d88',
    storageBucket: 'calendarapp-86d88.appspot.com',
    messagingSenderId: '229643626573',
    appId: '1:229643626573:web:efa0c31f1c81eec5ec5404'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgkukQGb20RhCA-jt_FtL63drdeA9eXU',
    iosBundleId: 'com.example.calendarioMedico',
    appId: '1:229643626573:ios:3d3de5a49ff49003ec5404',
    storageBucket: 'calendarapp-86d88.appspot.com',
    messagingSenderId: '229643626573',
    iosClientId: '229643626573-sph0mquf4r7rol83l1sd6469766465pi.apps.googleusercontent.com',
    projectId: 'calendarapp-86d88'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRxgKRIDyb2Kud7x4HTT8ZnjUf3JxHtTk',
    appId: '1:229643626573:android:c8f3af833eba9779ec5404',
    messagingSenderId: '229643626573',
    projectId: 'calendarapp-86d88',
    storageBucket: 'calendarapp-86d88.appspot.com'
  );
}
